import { readFileSync, writeFileSync } from "node:fs";

const core = readFileSync(new URL("./source-core.js", import.meta.url), "utf8").replace(
  /^export /gm,
  "",
);
const wrapper = readFileSync(new URL("./source-wrapper.js", import.meta.url), "utf8");

const source = [
  "// Generated by chainlink/build-source.mjs. Edit source-core.js or source-wrapper.js.",
  "// x502 GitHub fact source — runs inside the Chainlink Functions DON (Deno).",
  'import { ethers } from "https://esm.sh/ethers@6.13.4";',
  "",
  core.trim(),
  "",
  wrapper.trim(),
  "",
].join("\n");

writeFileSync(new URL("./source.js", import.meta.url), source);
