// Generated by chainlink/build-source.mjs. Edit source-core.js or source-wrapper.js.
// x502 GitHub fact source — runs inside the Chainlink Functions DON (Deno).

const ZERO_ADDR = "0x0000000000000000000000000000000000000000";
const ZERO_B32 = `0x${"0".repeat(64)}`;

function labelsFromItem(item) {
  return (item?.labels || [])
    .map((label) => (typeof label === "string" ? label : label.name))
    .filter(Boolean);
}

function bytes32FromMask(mask) {
  if (mask === 0n) return ZERO_B32;
  return `0x${mask.toString(16).padStart(64, "0")}`;
}

function wordFromUint(value) {
  return BigInt(value).toString(16).padStart(64, "0");
}

function wordFromBytes32(value) {
  return value.replace(/^0x/, "").padStart(64, "0");
}

function wordFromAddress(value) {
  return value.replace(/^0x/, "").toLowerCase().padStart(64, "0");
}

function encodeFact(fact) {
  return `0x${[
    wordFromUint(fact.status),
    wordFromUint(fact.mergedBlock),
    wordFromBytes32(fact.labelMask),
    wordFromAddress(fact.ghAuthorBinding),
  ].join("")}`;
}

function hexToBytes(hex) {
  const clean = hex.replace(/^0x/, "");
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function githubHeaders(githubPat) {
  const headers = {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "x502-fact-receiver",
  };
  if (githubPat) headers.Authorization = `Bearer ${githubPat}`;
  return headers;
}

function parseRepoSlug(repoSlug) {
  const parts = repoSlug.split("/");
  if (parts.length !== 2 || !parts[0] || !parts[1]) throw Error("bad repoSlug");
  return { owner: parts[0], repo: parts[1] };
}

function authorBindingFromBody(body = "") {
  const match = body.match(/<!--\s*x502:(0x[a-fA-F0-9]{40})\s*-->/);
  return match ? match[1].toLowerCase() : ZERO_ADDR;
}

function mergedBlockFromSha(sha) {
  if (!sha) return 0n;
  return BigInt(`0x${sha.slice(0, 16)}`);
}

function decideFact({ kind, item, files = [] }) {
  const body = item?.body || "";
  const fact = {
    status: 0,
    mergedBlock: 0n,
    labelMask: ZERO_B32,
    ghAuthorBinding: authorBindingFromBody(body),
  };

  if (kind === 0) {
    const labels = labelsFromItem(item).map((label) => label.toLowerCase());
    const accepted =
      labels.includes("accepted") || labels.includes("bug") || labels.includes("enhancement");
    const rejected =
      labels.includes("wontfix") || labels.includes("duplicate") || labels.includes("invalid");

    fact.status = accepted && !rejected ? 1 : 0;

    let mask = 0n;
    if (labels.includes("bug")) mask |= 1n;
    if (labels.includes("enhancement")) mask |= 2n;
    if (labels.includes("accepted")) mask |= 4n;
    fact.labelMask = bytes32FromMask(mask);
    return fact;
  }

  if (kind === 1) {
    const labels = labelsFromItem(item);
    const normalizedLabels = labels.map((label) => label.toLowerCase());

    fact.status = labels.length >= 2 ? 1 : 0;

    let mask = 0n;
    if (normalizedLabels.includes("triage-done")) mask |= 8n;
    fact.labelMask = bytes32FromMask(mask);
    return fact;
  }

  if (kind === 2) {
    if (item && item.merged === true && /(?:fixes|closes|resolves)\s+#\d+/i.test(body)) {
      fact.status = 1;
      fact.mergedBlock = mergedBlockFromSha(item.merge_commit_sha);
    }
    return fact;
  }

  if (kind === 3) {
    if (item && item.merged === true) {
      const testRe = /(^|\/)(test|tests|spec|__tests__)\//i;
      const docRe = /(^|\/)(docs|readme)/i;
      const hasTest = files.some((file) => testRe.test(file.filename ?? ""));
      const hasDoc = files.some((file) => docRe.test(file.filename ?? ""));

      if (hasTest || hasDoc) {
        fact.status = 1;
        fact.mergedBlock = mergedBlockFromSha(item.merge_commit_sha);

        let mask = 0n;
        if (hasTest) mask |= 1n;
        if (hasDoc) mask |= 2n;
        fact.labelMask = bytes32FromMask(mask);
      }
    }
    return fact;
  }

  throw Error(`unknown kind ${kind}`);
}

const repoSlug = args[0];
const externalId = args[1];
const kind = parseInt(args[2], 10);
const { owner, repo } = parseRepoSlug(repoSlug);

const isPr = kind === 2 || kind === 3;
const endpoint = isPr ? "pulls" : "issues";

const headers = githubHeaders(secrets.GITHUB_PAT);

const r = await Functions.makeHttpRequest({
  url: `https://api.github.com/repos/${owner}/${repo}/${endpoint}/${externalId}`,
  headers,
  timeout: 9000,
});
if (r.error) throw Error(`gh ${endpoint}/${externalId} fetch failed: ${r.error}`);

let files = [];
if (kind === 3 && r.data && r.data.merged === true) {
  const fr = await Functions.makeHttpRequest({
    url: `https://api.github.com/repos/${owner}/${repo}/pulls/${externalId}/files`,
    headers,
    timeout: 9000,
  });
  if (!fr.error) files = fr.data ?? [];
}

const fact = decideFact({ kind, item: r.data, files });
return hexToBytes(encodeFact(fact));
